### ISSUE TITLE
Metrics description component

### ISSUE THREAD

**Issue by magland** [jsoules/othismos#7]
Description of metrics should be moved to markdown -- need to figure out rending of latex.

![image](https://user-images.githubusercontent.com/3679296/115014882-e7fc3480-9e80-11eb-9a47-5eb30c16a544.png)

**Comment by jsoules** [comment]
Looks like there are relevant tools for rendering both MarkDown and LaTeX in React; see https://levelup.gitconnected.com/adding-katex-and-markdown-in-react-7b70694004ef
I'll take a crack at this today.

**Comment by jsoules** [comment]
Actually https://www.npmjs.com/package/react-latex seems to have better syntax, and is also not being pushed by a website whose other tech articles are bitcoin scams, so maybe I'll try that one

**Comment by jsoules** [comment]
Closed by PR #14.
